// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nordax.Bank.Recruitment.DataAccess.DbContexts;

#nullable disable

namespace Nordax.Bank.Recruitment.DataAccess.Migrations.Option
{
    [DbContext(typeof(OptionDbContext))]
    partial class OptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Nordax.Bank.Recruitment.DataAccess.Entities.Option.BindingPeriod", b =>
                {
                    b.Property<int>("Length")
                        .HasPrecision(3)
                        .HasColumnType("int");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal(8,5)");

                    b.HasKey("Length");

                    b.ToTable("BindingPeriods");

                    b.HasData(
                        new
                        {
                            Length = 1,
                            InterestRate = 2m
                        },
                        new
                        {
                            Length = 3,
                            InterestRate = 2.3m
                        },
                        new
                        {
                            Length = 6,
                            InterestRate = 2.8m
                        },
                        new
                        {
                            Length = 12,
                            InterestRate = 3.3m
                        },
                        new
                        {
                            Length = 24,
                            InterestRate = 4m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
